my_project:
  outputs:
    dev:
      dbname: weather_data
      host: db
      pass: system
      port: 5432
      schema: dev
      threads: 4
      type: postgres
      user: postgres
  target: dev
